[features]
seeds = false
skip-lint = false
[programs.localnet]
orb = "FtoHTcr7Khzp7DcYSEDw5QN2pFYbMipohBsGcNjrqRZ7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/sushi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
